eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

spring:
  config:
    import: optional:configserver:http://localhost:1000

variable : ${user-service.message}

# Enable spring boot actuator to reload properties dynamically
management:
  endpoints:
    web:
      exposure:
        include: "*"